version: '3.8'

services:
  weather-api-1:
    build: .
    ports:
      - "8001:8000"
    environment:
      - CONTAINER_ID=1
    volumes:
      - ./uploaded_data:/app/uploaded_data
      - ./load_test_results:/app/load_test_results
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/status"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'

  weather-api-2:
    build: .
    ports:
      - "8002:8000"
    environment:
      - CONTAINER_ID=2
    volumes:
      - ./uploaded_data:/app/uploaded_data
      - ./load_test_results:/app/load_test_results
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/status"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'

  weather-api-3:
    build: .
    ports:
      - "8003:8000"
    environment:
      - CONTAINER_ID=3
    volumes:
      - ./uploaded_data:/app/uploaded_data
      - ./load_test_results:/app/load_test_results
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/status"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - weather-api-1
      - weather-api-2
      - weather-api-3
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'